apiVersion: apps/v1
kind: Deployment
metadata:
  name: staticws-deployment
  labels:
    app: staticws  
spec:
  selector:
    matchLabels:
      app: staticws
  replicas: 10
  template:
    metadata:
      labels:
        app: staticws
    spec:
      containers:
      - name: staticws
        image: sim007/staticws:latest
        #imagePullPolicy: Always
        ports:
        -  containerPort: 80 
